/* SunderMud 2.0. Please view the license before compiling. */
/* This file is auto-generated by ../bin/autosetup          */
/* Maximum characters per account. */
#define MAX_CHARS 20
/* Maximum members per group. */
#define MAX_GMEMBERS 10
/* A number of aliases (recommended 20) per user */
#define MAX_ALIAS 20
